version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    restart: on-failure
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_URL: postgres://user:password@db:5432/password_manager?sslmode=disable
      ENCRYPT_KEY: ${ENCRYPT_KEY}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password_manager
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
